# NUMBER MEANINGS
# 0 = unidentified
# 1 = credits
# 2 = regular text
# 3 = hymn
# 4 = P: C:
# 5 = insert empty scene
# 6 = service name
# 7 = lords prayer
# 8 = special music
# FORMAT
# case = number
cases = [
    [10, "Acknowledgment of the Land"],
    [3, "#"],
    [3, "Choir:"],
    [5, "Announcements"],
    [5, "Blessing"],
    [5, "Sermon"],
    [5, "Sharing of the Peace"],
    [2, "Dismissal"],
    [2, "Confession & Forgiveness"],
    [7, "Lord’s Prayer"],
    [9, "P:"],
    [9, "C:"],
    [9, "R:"],
    [10, "Genesis"],
	[10, "Exodus"],
	[10, "Leviticus"],
	[10, "Numbers"],
	[10, "Deuteronomy"],
	[10, "Joshua"],
	[10, "Judges"],
	[10, "Ruth"],
	[10, "Samuel"],
	[10, "Kings"],
	[10, "Chronicles"],
	[10, "Ezra"],
	[10, "Nehemiah"],
	[10, "Esther"],
	[10, "Job"],
	[10, "Psalm"],
	[10, "Proverbs"],
	[10, "Ecclesiastes"],
	[10, "Song of Solomon"],
	[10, "Isaiah"],
	[10, "Jeremiah"],
	[10, "Lamentations"],
	[10, "Ezekiel"],
	[10, "Daniel"],
	[10, "Hosea"],
	[10, "Joel"],
	[10, "Amos"],
	[10, "Obadiah"],
	[10, "Jonah"],
	[10, "Micah"],
	[10, "Nahum"],
	[10, "Habakkuk"],
	[10, "Zephaniah"],
	[10, "Haggai"],
	[10, "Zechariah"],
	[10, "Malachi"],
	[10, "Matthew"],
	[10, "Mark"],
	[10, "Luke"],
	[10, "Acts"],
	[10, "Romans"],
	[10, "Corinthians"],
	[10, "Galatians"],
	[10, "Ephesians"],
	[10, "Philippians"],
	[10, "Colossians"],
	[10, "Thessalonians"],
	[10, "Timothy"],
	[10, "Titus"],
	[10, "Philemon"],
	[10, "Hebrews"],
	[10, "James"],
	[10, "Peter"],
	[10, "John"],
	[10, "Jude"],
	[10, "Revelation"],
]